import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Search.module.css'
import Navigation from '../Components/Navbar'
import Main from '../Components/MainConent'
import LookupForm from '../Components/Lookup'
import { Form, Button, } from 'react-bootstrap'

const Search = () => {
    return ( 
<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>

      <main className={styles.main}>
        <LookupForm/>
      </main>

    </div>
     );
}
 
export default Search;